/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SWING;

import EVENTOS_USUARIOS.Usuario;
import EVENTOS_USUARIOS.UsuariosMetodos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;

/**
 *
 * @author vanes
 */
public class AdminUsuario_Menu extends javax.swing.JFrame {

    private ArrayList<Usuario> usuariosArray;
    private String name;
    private UsuariosMetodos funcionUsuario;

    public AdminUsuario_Menu(ArrayList<Usuario> usuarios, String name, UsuariosMetodos UsuarioFuncion) {
        usuariosArray = usuarios != null ? usuarios : new ArrayList<Usuario>();
        usuariosArray = Login.getUsuariosArray();
        this.name = name;
        funcionUsuario = UsuarioFuncion != null ? UsuarioFuncion : new UsuariosMetodos();

        initComponents();

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegresarBTN = new javax.swing.JButton();
        BorrarUsuarioBTN = new javax.swing.JButton();
        EditarUsuarioBTN = new javax.swing.JButton();
        CrearUsuarioBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegresarBTN.setContentAreaFilled(false);
        RegresarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarBTNActionPerformed(evt);
            }
        });
        getContentPane().add(RegresarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 180, 50));

        BorrarUsuarioBTN.setContentAreaFilled(false);
        BorrarUsuarioBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarUsuarioBTNActionPerformed(evt);
            }
        });
        getContentPane().add(BorrarUsuarioBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 240, 240));

        EditarUsuarioBTN.setContentAreaFilled(false);
        EditarUsuarioBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarUsuarioBTNActionPerformed(evt);
            }
        });
        getContentPane().add(EditarUsuarioBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 240, 240));

        CrearUsuarioBTN.setContentAreaFilled(false);
        CrearUsuarioBTN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                CrearUsuarioBTNMouseMoved(evt);
            }
        });
        CrearUsuarioBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearUsuarioBTNActionPerformed(evt);
            }
        });
        getContentPane().add(CrearUsuarioBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 250, 240));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/BG_AdminUsuarios.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarBTNActionPerformed
        int usuarioEleccion = JOptionPane.showConfirmDialog(null, "Desea regresar al menu principal?", "REGRESAR AL MENU", JOptionPane.YES_NO_OPTION);

        if (usuarioEleccion == JOptionPane.YES_OPTION) {
            MainMenu_Admin pasar = new MainMenu_Admin(usuariosArray, name, funcionUsuario);
            pasar.setVisible(true);
            this.setVisible(false);
            
        } else if (usuarioEleccion== JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(null, "Se canceló la operación.");
        }
    }//GEN-LAST:event_RegresarBTNActionPerformed

    private void CrearUsuarioBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearUsuarioBTNActionPerformed
        CrearUsuario_Admin pasar = new CrearUsuario_Admin(usuariosArray, name, funcionUsuario);
        pasar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CrearUsuarioBTNActionPerformed

    private void CrearUsuarioBTNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearUsuarioBTNMouseMoved
        CrearUsuarioBTN.setToolTipText("Menu para crear usuarios.");
    }//GEN-LAST:event_CrearUsuarioBTNMouseMoved

    private void EditarUsuarioBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarUsuarioBTNActionPerformed
        String usuarioViejo = JOptionPane.showInputDialog(null, "Inserte el usuario que desea editar.");
        String passwordViejo = JOptionPane.showInputDialog(null, "Inserte la contraseña del usuario.");
        
        
        boolean usuario = funcionUsuario.revisarUsuario(usuarioViejo, passwordViejo );

        if (usuario){
        EditarUsuario_Admin pasar = new EditarUsuario_Admin(usuariosArray, "", funcionUsuario, usuarioViejo, passwordViejo);
        pasar.setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_EditarUsuarioBTNActionPerformed



    private void BorrarUsuarioBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarUsuarioBTNActionPerformed
        EliminarUsuario_Admin pasar = new EliminarUsuario_Admin(usuariosArray, name, funcionUsuario);
        pasar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BorrarUsuarioBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUsuario_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUsuario_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUsuario_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUsuario_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUsuario_Menu(new ArrayList<Usuario>(), "", new UsuariosMetodos()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BorrarUsuarioBTN;
    private javax.swing.JButton CrearUsuarioBTN;
    private javax.swing.JButton EditarUsuarioBTN;
    private javax.swing.JButton RegresarBTN;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
