/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SWING;

import EVENTOS_USUARIOS.Evento;
import EVENTOS_USUARIOS.EventoDeportivo;
import EVENTOS_USUARIOS.EventoDeportivo.TipoDeporte;
import EVENTOS_USUARIOS.EventosMetodos;
import EVENTOS_USUARIOS.Usuario;
import EVENTOS_USUARIOS.UsuariosMetodos;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author vanes
 */
public class DetallesDeportivo extends javax.swing.JFrame {

    private ArrayList<Usuario> usuariosArray;
    private String name;
    private String codigoEvento;
    private EventosMetodos funcionEvento;
    private EventoDeportivo deportivoEvento;
    String tipoDeporte;

    public DetallesDeportivo(String name, EventosMetodos EventoFuncion, String codigoEvento) {
        usuariosArray = Login.getUsuariosArray();
        this.name = name;
        this.codigoEvento = codigoEvento;
        funcionEvento = EventoFuncion != null ? EventoFuncion : new EventosMetodos();

        initComponents();

        for (int indice = 0; indice < usuariosArray.size(); indice++) {
            if (usuariosArray.get(indice).getUsuario().equals(name)) {
                ArrayList<Evento> eventos = usuariosArray.get(indice).getListaEventos();
                for (Evento evento : eventos) {
                    if (evento.getCodigo().equals(codigoEvento)) {
                        EventoDeportivo deportivoEvento = (EventoDeportivo) evento;
                        Equipo1Textbox.setText(((EventoDeportivo) evento).getEquipo1());
                        Equipo2Textbox.setText(((EventoDeportivo) evento).getEquipo2());
                        tipoDeporte = ((EventoDeportivo) evento).getTipoDeporte().toString();
                        jComboBox1.setSelectedItem(((EventoDeportivo) evento).getTipoDeporte());
                    }
                }
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        RegresarBTN = new javax.swing.JButton();
        Equipo1Textbox = new javax.swing.JTextField();
        JugadorTextbox11 = new javax.swing.JTextField();
        JugadorTextbox12 = new javax.swing.JTextField();
        JugadorTextbox13 = new javax.swing.JTextField();
        JugadorTextbox14 = new javax.swing.JTextField();
        JugadorTextbox15 = new javax.swing.JTextField();
        Equipo2Textbox = new javax.swing.JTextField();
        JugadorTextbox21 = new javax.swing.JTextField();
        JugadorTextbox22 = new javax.swing.JTextField();
        JugadorTextbox23 = new javax.swing.JTextField();
        JugadorTextbox24 = new javax.swing.JTextField();
        JugadorTextbox25 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setBackground(new java.awt.Color(245, 245, 245));
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new DefaultComboBoxModel<>(TipoDeporte.values()));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 220, 30));

        RegresarBTN.setContentAreaFilled(false);
        RegresarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarBTNActionPerformed(evt);
            }
        });
        getContentPane().add(RegresarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 480, 51));

        Equipo1Textbox.setEditable(false);
        Equipo1Textbox.setBackground(new java.awt.Color(245, 245, 245));
        Equipo1Textbox.setForeground(new java.awt.Color(0, 0, 0));
        Equipo1Textbox.setBorder(null);
        getContentPane().add(Equipo1Textbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 200, 30));

        JugadorTextbox11.setEditable(false);
        JugadorTextbox11.setBackground(new java.awt.Color(245, 245, 245));
        JugadorTextbox11.setForeground(new java.awt.Color(0, 0, 0));
        JugadorTextbox11.setBorder(null);
        getContentPane().add(JugadorTextbox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 200, 30));

        JugadorTextbox12.setEditable(false);
        JugadorTextbox12.setBackground(new java.awt.Color(245, 245, 245));
        JugadorTextbox12.setForeground(new java.awt.Color(0, 0, 0));
        JugadorTextbox12.setBorder(null);
        JugadorTextbox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugadorTextbox12ActionPerformed(evt);
            }
        });
        getContentPane().add(JugadorTextbox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 200, 30));

        JugadorTextbox13.setEditable(false);
        JugadorTextbox13.setBackground(new java.awt.Color(245, 245, 245));
        JugadorTextbox13.setForeground(new java.awt.Color(0, 0, 0));
        JugadorTextbox13.setBorder(null);
        JugadorTextbox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugadorTextbox13ActionPerformed(evt);
            }
        });
        getContentPane().add(JugadorTextbox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 200, 30));

        JugadorTextbox14.setEditable(false);
        JugadorTextbox14.setBackground(new java.awt.Color(245, 245, 245));
        JugadorTextbox14.setForeground(new java.awt.Color(0, 0, 0));
        JugadorTextbox14.setBorder(null);
        getContentPane().add(JugadorTextbox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 200, 30));

        JugadorTextbox15.setEditable(false);
        JugadorTextbox15.setBackground(new java.awt.Color(245, 245, 245));
        JugadorTextbox15.setForeground(new java.awt.Color(0, 0, 0));
        JugadorTextbox15.setBorder(null);
        getContentPane().add(JugadorTextbox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 200, 30));

        Equipo2Textbox.setEditable(false);
        Equipo2Textbox.setBackground(new java.awt.Color(245, 245, 245));
        Equipo2Textbox.setForeground(new java.awt.Color(0, 0, 0));
        Equipo2Textbox.setBorder(null);
        getContentPane().add(Equipo2Textbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 200, 30));

        JugadorTextbox21.setEditable(false);
        JugadorTextbox21.setBackground(new java.awt.Color(245, 245, 245));
        JugadorTextbox21.setForeground(new java.awt.Color(0, 0, 0));
        JugadorTextbox21.setBorder(null);
        getContentPane().add(JugadorTextbox21, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 200, 30));

        JugadorTextbox22.setEditable(false);
        JugadorTextbox22.setBackground(new java.awt.Color(245, 245, 245));
        JugadorTextbox22.setForeground(new java.awt.Color(0, 0, 0));
        JugadorTextbox22.setBorder(null);
        JugadorTextbox22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugadorTextbox22ActionPerformed(evt);
            }
        });
        getContentPane().add(JugadorTextbox22, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 200, 30));

        JugadorTextbox23.setEditable(false);
        JugadorTextbox23.setBackground(new java.awt.Color(245, 245, 245));
        JugadorTextbox23.setForeground(new java.awt.Color(0, 0, 0));
        JugadorTextbox23.setBorder(null);
        getContentPane().add(JugadorTextbox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 190, 30));

        JugadorTextbox24.setEditable(false);
        JugadorTextbox24.setBackground(new java.awt.Color(245, 245, 245));
        JugadorTextbox24.setForeground(new java.awt.Color(0, 0, 0));
        JugadorTextbox24.setBorder(null);
        JugadorTextbox24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugadorTextbox24ActionPerformed(evt);
            }
        });
        getContentPane().add(JugadorTextbox24, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 200, 30));

        JugadorTextbox25.setEditable(false);
        JugadorTextbox25.setBackground(new java.awt.Color(245, 245, 245));
        JugadorTextbox25.setForeground(new java.awt.Color(0, 0, 0));
        JugadorTextbox25.setBorder(null);
        getContentPane().add(JugadorTextbox25, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 200, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/BG_EditarDeportivo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JugadorTextbox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugadorTextbox12ActionPerformed

    }//GEN-LAST:event_JugadorTextbox12ActionPerformed

    private void RegresarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarBTNActionPerformed

        for (int indice = 0; indice < usuariosArray.size(); indice++) {

            if (usuariosArray.get(indice).getUsuario().equals(name)) {

                ArrayList<Evento> eventos = usuariosArray.get(indice).getListaEventos();
                for (Evento evento : eventos) {
                    if (evento.getCodigo().equals(codigoEvento)) {
                        deportivoEvento = (EventoDeportivo) evento;
                    }
                }
            }
        }

        ArrayList<String> jugadores1 = new ArrayList<>();
        ArrayList<String> jugadores2 = new ArrayList<>();

        String nuevoEquipo1 = Equipo1Textbox.getText();

        String nuevoEquipo2 = Equipo2Textbox.getText();

        String jugador = JugadorTextbox11.getText();

        if (!jugador.isEmpty()) {
            jugadores1.add(jugador);

        }

        jugador = JugadorTextbox12.getText();

        if (!jugador.isEmpty()) {
            jugadores1.add(jugador);

        }

        jugador = JugadorTextbox13.getText();

        if (!jugador.isEmpty()) {
            jugadores1.add(jugador);

        }

        jugador = JugadorTextbox14.getText();

        if (!jugador.isEmpty()) {
            jugadores1.add(jugador);

        }

        jugador = JugadorTextbox15.getText();

        if (!jugador.isEmpty()) {
            jugadores1.add(jugador);

        }

        jugador = JugadorTextbox21.getText();

        if (!jugador.isEmpty()) {
            jugadores2.add(jugador);

        }

        jugador = JugadorTextbox22.getText();

        if (!jugador.isEmpty()) {
            jugadores2.add(jugador);

        }

        jugador = JugadorTextbox23.getText();

        if (!jugador.isEmpty()) {
            jugadores2.add(jugador);

        }

        jugador = JugadorTextbox24.getText();

        if (!jugador.isEmpty()) {
            jugadores2.add(jugador);

        }

        jugador = JugadorTextbox25.getText();

        if (!jugador.isEmpty()) {
            jugadores2.add(jugador);

        }
        for (int indice = 0; indice < usuariosArray.size(); indice++) {
            if (usuariosArray.get(indice).getUsuario().equals(name)) {
                ArrayList<Evento> eventos = usuariosArray.get(indice).getListaEventos();
                for (Evento evento : eventos) {
                    if (evento.getCodigo().equals(codigoEvento)) {
                        EventoDeportivo deportivoEvento = (EventoDeportivo) evento;
                        Object selectedItem = jComboBox1.getSelectedItem();
                        tipoDeporte = (selectedItem != null) ? selectedItem.toString() : null;
                    }
                }
            }
        }

        if ((!JugadorTextbox12.getText().isEmpty()
                || !JugadorTextbox13.getText().isEmpty()
                || !JugadorTextbox14.getText().isEmpty()
                || !JugadorTextbox15.getText().isEmpty())
                && (!JugadorTextbox21.getText().isEmpty()
                || !JugadorTextbox22.getText().isEmpty()
                || !JugadorTextbox23.getText().isEmpty()
                || !JugadorTextbox24.getText().isEmpty()
                || !JugadorTextbox25.getText().isEmpty())) {
            
            this.dispose();
            
        } else {
            
            JOptionPane.showMessageDialog(null, "Por favor, inserta minimo UN jugador de cada equipo.");
        }
    }//GEN-LAST:event_RegresarBTNActionPerformed

    private void JugadorTextbox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugadorTextbox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JugadorTextbox13ActionPerformed

    private void JugadorTextbox22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugadorTextbox22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JugadorTextbox22ActionPerformed

    private void JugadorTextbox24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugadorTextbox24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JugadorTextbox24ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetallesDeportivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetallesDeportivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetallesDeportivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetallesDeportivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetallesDeportivo("", new EventosMetodos(), "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Equipo1Textbox;
    private javax.swing.JTextField Equipo2Textbox;
    private javax.swing.JTextField JugadorTextbox11;
    private javax.swing.JTextField JugadorTextbox12;
    private javax.swing.JTextField JugadorTextbox13;
    private javax.swing.JTextField JugadorTextbox14;
    private javax.swing.JTextField JugadorTextbox15;
    private javax.swing.JTextField JugadorTextbox21;
    private javax.swing.JTextField JugadorTextbox22;
    private javax.swing.JTextField JugadorTextbox23;
    private javax.swing.JTextField JugadorTextbox24;
    private javax.swing.JTextField JugadorTextbox25;
    private javax.swing.JButton RegresarBTN;
    private javax.swing.JComboBox<TipoDeporte> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
